web:
    build: .
    links:
     - mysql
    ports:
     - "127.0.0.4:8080:80"
mysql:
    image: mysql:latest
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=cagette
    working_dir: /var/lib/mysql
    volumes:
        - ./database:/var/lib/mysql

